Widening return type hint of SimpleCacheDecorator::translateThrowable method
laminas/laminas-cache pull request #169
Opened 2021-10-24 03:30 UTC by mariojrrc

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Tell us about why this change is necessary:
- Are you fixing a bug or providing a failing unit test to demonstrate a bug?
no
- How do you reproduce it?
Set up a Filesystem adapter and try to call has/get/set methods of Laminas\Cache\Psr\SimpleCache\SimpleCacheDecorator passing an invalid key such as '127.0.0.1'

- What did you expect to happen?
It should throws the Laminas\Cache\Psr\SimpleCache\SimpleCacheInvalidArgumentException with message "The key '127.0.0.1' doesn't match against pattern '/^[a-z0-9_\\+\\-]*$/Di'"

- What actually happened?
It throws a TypeError exception with the following message: 

"Return value of Laminas\\Cache\\Psr\\SimpleCache\\SimpleCacheDecorator::translateThrowable() must be an instance of Laminas\\Cache\\Psr\\SimpleCache\\SimpleCacheException, instance of Laminas\\Cache\\Psr\\SimpleCache\\SimpleCacheInvalidArgumentException returned"

- TARGET THE 2.13.x BRANCH

2021-10-25 07:33 UTC, boesing requested changes
Thanks for pointing out that issue.
Could you please also create a failing test case? There should be no need of the filesystem adapter to trigger this method.

2021-10-25 07:33 UTC, boesing commented on src/Psr/SimpleCache/SimpleCacheDecorator.php
> +    private static function translateThrowable(Throwable $throwable)
Instead of removing the type-hint, we should open-up the type-hint to `Psr\SimpleCache\CacheException`.
Thats the interface which has to get implemented by all exceptions which are thrown from any PSR-16 implementation.

2021-10-25 13:46 UTC, mariojrrc commented on src/Psr/SimpleCache/SimpleCacheDecorator.php
> +    private static function translateThrowable(Throwable $throwable)
You're right. I'm gonna update that.

2021-10-25 14:14 UTC, mariojrrc commented on src/Psr/SimpleCache/SimpleCacheDecorator.php
> +    private static function translateThrowable(Throwable $throwable)
@boesing before my modificacion a simple failing test looks like this.

```
public function testWillThrowExceptionWhenUsingFilesystemAdapterAndUseInvalidCacheKey(): void
    {
        $storage = StorageFactory::factory([
            'adapter' => 'filesystem',
            'plugins' => ['Serializer'],
        ]);

        $this->assertInstanceOf(Filesystem::class, $storage);

        $decorator = new SimpleCacheDecorator($storage);

        $this->expectException(InvalidArgumentException::class);
        $decorator->get('127.0.0.1');
    }
```

The expected exception will not be thrown. Instead of it will throw a TypeError exception.

After my modification the test will pass.

2021-10-25 14:16 UTC, boesing commented on src/Psr/SimpleCache/SimpleCacheDecorator.php
> +    private static function translateThrowable(Throwable $throwable)
Can you please commit this failing test to the repository? Please avoid using the `StorageFactory` (which will be removed with v3) and instead simply use:

```php
$storage = new Filesystem();
$storage->addPlugin(new Serializer());
```

2021-10-25 14:25 UTC, mariojrrc commented on src/Psr/SimpleCache/SimpleCacheDecorator.php
> +    private static function translateThrowable(Throwable $throwable)
@boesing I made the requested changes.

2021-10-25 14:43 UTC, boesing requested changes
LGTM - just a little nitpick regarding the import statement.

2021-10-25 14:43 UTC, boesing commented on src/Psr/SimpleCache/SimpleCacheDecorator.php
> +use Psr\SimpleCache\CacheException as PsrCacheException;
Could you use `as SimpleCacheExceptionInterface` instead? 
We do use `as SimpleCacheInterface` below so we keep at least some conformity?

Thanks for working on this 👍🏼

2021-10-25 14:52 UTC, mariojrrc commented on src/Psr/SimpleCache/SimpleCacheDecorator.php
> +use Psr\SimpleCache\CacheException as PsrCacheException;
Sure, thats makes total sense :)

2021-10-26 23:28 UTC, mariojrrc commented on src/Psr/SimpleCache/SimpleCacheDecorator.php
> +use Psr\SimpleCache\CacheException as PsrCacheException;
@boesing is there any other point to make changes?

2021-11-07 10:47 UTC, merged

2021-11-07 10:47 UTC, boesing commented
Thanks, @mariojrrc 
Sorry that it took that long.