all datatypes for blackhole adapter
laminas/laminas-cache pull request #26
Opened 2020-07-16 06:45 UTC by JesBei

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

```PHP
...could not be created. Reason: The storage adapter "Zend\Cache\Storage\Adapter\BlackHole" requires a serializer plugin; please see https://docs.zendframework.com/zend-cache/storage/plugin/#quick-start for details on how to attach the plugin to your adapter.
```

```PHP
... could not be created. Reason: The adapter 'Zend\Cache\Storage\Adapter\BlackHole' doesn't implement 'Zend\EventManager\EventsCapableInterface' and therefore can't handle plugins
```

Blackhole adapter now accepts all datatypes and doesn't need a serializer anymore. Otherwise you have to implement the EventSystem but I don't think that's necessary because blackhole doesn't save anything anyway.

2020-07-16 06:53 UTC, michalbundyra requested changes
@JesBei Thanks for your contribution.

In order to accept the PR we need unit test to be added to cover the changes.
Also please revert all unrelated formatting changes and check DCO status. Thanks.

2020-07-16 11:56 UTC, fabiang commented
Btw: the error described by @JesBei happens when using the PSR-16 decorator, which leaves the Blackhole adapter unusable together with PSR-16.

2020-07-16 12:42 UTC, JesBei commented
> @JesBei Thanks for your contribution.
> 
> In order to accept the PR we need unit test to be added to cover the changes.
> Also please revert all unrelated formatting changes and check DCO status. Thanks.

Added the Unit Test and reverted the formatting.

2020-07-20 19:33 UTC, boesing commented
@JesBei Could you please add integration tests for Blackhole aswell?
There are several integration tests in the `tests/Psr` directory, you can just copy & paste one of these and apply changes to use the Blackhole adapter.

As @fabiang states, there is an issue with the PSR decorators. Thus, with those tests, we would have initial failing tests aswell.

I will move those changes to [laminas/laminas-cache-storage-adapter-blackhole](https://github.com/laminas/laminas-cache-storage-adapter-blackhole) in case we are fixing that "issue" in a patch version. If not, these changes will definitely be part of the 2.10 milestone.

2020-08-25 12:57 UTC, fabiang commented
> @JesBei Could you please add integration tests for Blackhole aswell?
> There are several integration tests in the `tests/Psr` directory, you can just copy & paste one of these and apply changes to use the Blackhole adapter.

The integration tests does make much sense, since the blackhole adapter doesn't cache anything and as a result the test that come from https://github.com/php-cache/integration-tests should fail. The only reasonable test could be that the decorators can handle the adapter and imho this could be done in the unit test directly.

2020-09-15 19:43 UTC, boesing commented
@JesBei I have to revert my latest statement, that this will be definetely be part of the next minor (2.10.0).
The next minor version (2.10.0) of laminas-cache will introduce satellite packages for all storage adapters. Thus, I have to close PRs in here which point to adapters.

If you still need support for this feature, please fork [laminas/laminas-cache-storage-adapter-blackhole](https://github.com/laminas/laminas-cache-storage-adapter-blackhole) and re-open a PR in the adapter project.

2020-09-15 19:43 UTC, closed without merging