Documentation: Add `ssl_context` option to `RedisCluster` documentation
laminas/laminas-cache pull request #300
Opened 2024-04-16 09:32 UTC by boesing

|    Q          |   A
|-------------- | ------
| Documentation | yes

### Description

This adds the documentation of the new created `ssl_options` option flag for `RedisCluster` options.
Closes #299 
Is a new patch version feasible, this component does actually not change at all.

2024-04-18 08:10 UTC, froschdesign requested changes

2024-04-18 08:10 UTC, froschdesign commented on docs/book/v3/storage/adapter.md
> +| `namespace_separator` | `string`                  | ":"           | A separator for the namespace and prefix.
```suggestion
| `namespace_separator` | `string`                  | `:`           | A separator for the namespace and prefix.                                                                                                                                                                                                          |
```

2024-04-18 08:10 UTC, froschdesign commented on docs/book/v3/storage/adapter.md
> +| `password`            | `string`                  | ""            | Password to authenticate with Redis server
I suggest a comment like "(empty)" as the default value.

2024-04-18 08:10 UTC, froschdesign commented on docs/book/v3/storage/adapter.md
> +| `name`                | `string`                  | ""            | Name to determine configuration from [php.ini](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#loading-a-clust
The same suggestion here.

2024-04-18 08:10 UTC, froschdesign commented on docs/book/v3/storage/adapter.md
> +| `version`             | `string`                  | ""            | The Redis server version. **MUST** be specified in a [Semantic Versioning 2.0.0](https://semver.org/#semantic-versioning-200) for
And here.

2024-06-14 13:39 UTC, boesing commented
@froschdesign I keep the suggestions here open as they should be done indeed but actually only appeared due to the fact that I reformatted all the tables to match markdown codingstyle. Contents where not changed by me and thus lets keep this focused on adding `ssl_context`.

I am still unhappy with the way how adapter configuration has to be maintained. 
I raised this concern a lot yet I am unable to provide useful input. 
The main pain points for me are:
- cross repository changes
- changes which do not reflect adapter versioning (there are multiple majors in several adapters)

I'd like to still see all the docs regarding an adapter listed in the appropriate satellites. So we can provide dedicated cache page the same way we do for https://docs.laminas.dev/mvc/
This would allow us to have every (supported) adapter listed on that page individually in dedicated versionings.
No idea how we did that for MVC but IMHO it should look like that so that we finally can provide feature documentation from within the adapter repository and do not have cross repository PRs such as these.

This said, I will merge this for now so that we have the SSL context properly documented.

2024-06-14 13:39 UTC, merged