docs: add example `composer.json`
laminas/laminas-cache pull request #81
Opened 2021-04-02 17:23 UTC by boesing

|    Q          |   A
|-------------- | ------
| Documentation | yes

### Description

With this example, it is possible to only require those adapters which are required by the project.

2021-04-07 05:58 UTC, froschdesign commented
@boesing 
_Sorry for the late response!_

These are migration notes, right? I would suggest to create a page in the documentation and add this information there. Additionally, a link to the migration page should be added in the readme file.

2021-04-07 09:19 UTC, boesing commented
@froschdesign No, this is just an information on how to configure a current 2.10 based project to not install all unnecessary cache adapters pre-3.0.
I dont think we can provide PHP 8 support to all adapters as most of them are already not supported on PHP 7 either.

So, we dont have to migrate all adapters to PHP 8 at once and let people decide on which adapters they use and to provide PRs only for these adapters.

So in the end, it is forward compatibility to 3.0 aswell as PHP 8 not having to be supported on every adapter for 2.10+.
Thats the idea behind this example.

2021-04-07 09:25 UTC, froschdesign commented
> No, this is just an information on how to configure a current 2.10 based project to not install all unnecessary cache adapters pre-3.0.

Then the description with the example should be added to the installation page.

2021-04-07 10:22 UTC, boesing commented
@froschdesign Just to be sure I understand this correct, we dont want to provide informations in `README.md` but via docs only? 

I've also seen that this package is not using the `installation` template other packages are using. So yes, I can extend the installation page here, but how to achieve that in packages which are using the installation template?
Shouldn't we use the template in each package?

2021-04-07 10:47 UTC, froschdesign commented
@boesing 
> Just to be sure I understand this correct, we dont want to provide informations in `README.md` but via docs only?

Oh no. In the optimum case we should provide the same informations (like intro, installation, etc.) in the readme file (here on GitHub and after the installation in the vendor directory) and in the documentation, without duplicating the content. Because duplicating always leads to forgotten updates on one side.
So far, we don't have a (good) solution for this, so it reduces to some text and links.

> Shouldn't we use the template in each package?

Yes. I would provide a solution that allows custom content to be added, like the Composer configuration.

2021-04-26 07:18 UTC, froschdesign requested changes
Some small changes are needed:

* For headline we uses the "[Chicago Manual of Style Capitalization Rules](https://capitalizemytitle.com/#ChicagoStyle)"
* [MD022 - Headings should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022)

2021-04-26 07:18 UTC, froschdesign commented on README.md
> +With `laminas-cache` v2.10.0, we introduced satellite packages for all cache adapters.
```suggestion
## Avoid Unused Cache Adapters Are Being Installed

With `laminas-cache` v2.10.0, we introduced satellite packages for all cache adapters.
```

2021-04-26 07:18 UTC, froschdesign commented on README.md
> +```json
```suggestion
### Example `composer.json` with Only Memory Adapter Being Installed

```json
```

2021-04-26 07:18 UTC, froschdesign commented on README.md
> +> Starting with 3.0.0, no storage adapter is required by this component and thus, each project has to specify the storage adapters which are required by the project.
```suggestion
> ### Only necessary in 2.10+
>
> Starting with 3.0.0, no storage adapter is required by this component and thus, each project has to specify the storage adapters which are required by the project.
```

2021-04-26 07:18 UTC, froschdesign commented on docs/book/installation.md
> +With `laminas-cache` v2.10.0, we introduced satellite packages for all cache adapters.
```suggestion
## Avoid Unused Cache Adapters Are Being Installed

With `laminas-cache` v2.10.0, we introduced satellite packages for all cache adapters.
```

2021-04-26 07:18 UTC, froschdesign commented on docs/book/installation.md
> +> Starting with 3.0.0, no storage adapter is required by this component and thus, each project has to specify the storage adapters which are required by the project.
```suggestion
> ### Only necessary in 2.10+
>
> Starting with 3.0.0, no storage adapter is required by this component and thus, each project has to specify the storage adapters which are required by the project.
```

2021-04-26 07:18 UTC, froschdesign commented on docs/book/installation.md
> +```json
```suggestion
### Example `composer.json` with Only Memory Adapter Being Installed

```json
```

2021-04-26 07:18 UTC, froschdesign commented on docs/book/installation.md
> +> Starting with 3.0.0, no storage adapter is required by this component and thus, each project has to specify the storage adapters which are required by the project.
Move this block quote to the beginning as it breaks the example and all version 3 users can skip this part / information from the beginning.
(after the headline "Avoid Unused Cache Adapters Are Being Installed")

2021-04-26 07:18 UTC, froschdesign commented on README.md
> +> Starting with 3.0.0, no storage adapter is required by this component and thus, each project has to specify the storage adapters which are required by the project.
Move this block quote to the beginning as it breaks the example and all version 3 users can skip this part / information from the beginning.
(after the headline "Avoid Unused Cache Adapters Are Being Installed")

2021-04-26 13:04 UTC, boesing commented
Bummer! I sweared to myself that I will keep an eye on these chicago headlines 😂

2021-04-28 21:47 UTC, froschdesign approved these changes
🚢

2021-04-29 08:03 UTC, merged